version: '3'

services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: tiki
    ports:
      - 8080:80
    volumes:
      - .:/srv/www/app
    links:
      - mysql
    environment:
      DB_HOST: mysql
      DB_DATABASE: tiki
      DB_USERNAME: app
      DB_PASSWORD: password
  mysql:
    image: mysql:5.7
    ports:
      - 13306:3306
    environment:
      MYSQL_DATABASE: tiki
      MYSQL_USER: app
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
